import React from 'react';
import { LINE_MOTIFS } from './paths.js';

// Hand-drawn line motifs, generated by tools/line-art/generate.mjs.
//
// Stroke is currentColor on purpose: the same motif inverts on a dark section without a second asset.
// aria-hidden throughout — these carry no meaning a screen reader needs, they are ornament.
const LineMotif = ({ name, className = '', style, draw = false, ...rest }) => {
  const motif = LINE_MOTIFS[name];
  if (!motif) return null;

  return (
    <svg
      viewBox={motif.viewBox}
      className={`line-motif${draw ? ' line-motif--draw' : ''} ${className}`.trim()}
      style={style}
      aria-hidden="true"
      focusable="false"
      preserveAspectRatio="xMidYMid meet"
      {...rest}
    >
      {motif.strokes.map((stroke, index) => (
        <path
          key={index}
          d={stroke.d}
          fill="none"
          stroke="currentColor"
          strokeWidth={stroke.width}
          strokeLinecap="round"
          strokeLinejoin="round"
          opacity={stroke.opacity}
          style={draw ? { animationDelay: `${index * 140}ms` } : undefined}
        />
      ))}
    </svg>
  );
};

export const LineDivider = (props) => <LineMotif name="divider" {...props} />;
export const LineVessel = (props) => <LineMotif name="vessel" {...props} />;
export const LineScribble = (props) => <LineMotif name="scribble" {...props} />;
export const LineMark = (props) => <LineMotif name="mark" {...props} />;

export default LineMotif;
