-- Generated by apps/web/tools/generate-operational-material-library-sql.mjs
-- Source: C:\webapp\perfumers-workbook\exports\material-reference-no-dilute.json
BEGIN;

CREATE TEMP TABLE desired_reference_codes (
  reference_code text PRIMARY KEY
) ON COMMIT DROP;

INSERT INTO desired_reference_codes (reference_code)
VALUES
  ('0ZA01228'),
  ('0ZA01393'),
  ('0ZA01431'),
  ('0ZA01433'),
  ('0ZA01434'),
  ('0ZA01437'),
  ('0ZA01442'),
  ('0ZA01456'),
  ('0ZA07519'),
  ('0ZA07555'),
  ('0ZC00449'),
  ('0ZH20962'),
  ('0ZN00053'),
  ('0ZN00054'),
  ('0ZP00365'),
  ('0ZP03359'),
  ('0ZS05357'),
  ('0ZS07626'),
  ('0ZS07781'),
  ('0ZV01349'),
  ('0ZV01445'),
  ('0ZV01452'),
  ('0ZV01460'),
  ('0ZV22213'),
  ('0ZW00165'),
  ('0ZX00143'),
  ('0ZZ00239'),
  ('0ZZ00240'),
  ('0ZZ07723'),
  ('1AA05031'),
  ('1AA06214'),
  ('1BB00290'),
  ('1BH00080'),
  ('1BW00064'),
  ('1CN00320'),
  ('1CN00321'),
  ('1EN13109'),
  ('1FB00071'),
  ('1FL00392'),
  ('1NC00340'),
  ('1NP00009'),
  ('1PF01952'),
  ('1PS00442'),
  ('1RO05275'),
  ('1RP00051'),
  ('1RP05672'),
  ('1SP00011'),
  ('1SP00058'),
  ('1UW00035'),
  ('1UW00036'),
  ('1UW13850'),
  ('1UW16861'),
  ('1VD00002'),
  ('1VD00129'),
  ('1VE00283'),
  ('1VE00286'),
  ('1VF00175'),
  ('1VV00179'),
  ('1VW00456'),
  ('1WW00096'),
  ('1WW01281'),
  ('1XA00444'),
  ('1XD15945'),
  ('1XU00308'),
  ('1XY00101'),
  ('1YG00077'),
  ('1YP00185'),
  ('1ZX03525'),
  ('2CQ00168'),
  ('2GQ01781'),
  ('2NC00409'),
  ('2QC00337'),
  ('2QK00334'),
  ('2QK21856'),
  ('2QS00421'),
  ('2QV00050'),
  ('2QV00363'),
  ('2QV00443'),
  ('2QV08253'),
  ('2QZ00223'),
  ('2RB00163'),
  ('2SC00297'),
  ('2SQ00056'),
  ('2SV00105'),
  ('2UQ00264'),
  ('2VD00148'),
  ('2VN10848'),
  ('2WW00099'),
  ('2XA09558'),
  ('2XX00186'),
  ('2XX14556'),
  ('2YQ00329'),
  ('3AC03955'),
  ('3AD13388'),
  ('3AE13387'),
  ('3BH00078'),
  ('3BH00181'),
  ('3CC00112'),
  ('3CC06770'),
  ('3CK00150'),
  ('3CK07504'),
  ('3CQ00276'),
  ('3CQ00313'),
  ('3CR00317'),
  ('3FD00174'),
  ('3FD00246'),
  ('3FD04102'),
  ('3FD05860'),
  ('3FG00145'),
  ('3FG00172'),
  ('3FG00196'),
  ('3FG00387'),
  ('3FG00463'),
  ('3FG19149'),
  ('3FH04104'),
  ('3FL06757'),
  ('3GF19243'),
  ('3GM00219'),
  ('3GN00227'),
  ('3GN00379'),
  ('3GO00229'),
  ('3GS16129'),
  ('3IA00343'),
  ('3IA06874'),
  ('3IF00237'),
  ('3IF00238'),
  ('3IL00139'),
  ('3IL00153'),
  ('3IW00300'),
  ('3JF00052'),
  ('3JF00059'),
  ('3JF07351'),
  ('3JJ00005'),
  ('3JJ00217'),
  ('3JJ00218'),
  ('3JN00258'),
  ('3KC00386'),
  ('3KC00431'),
  ('3KC14406'),
  ('3KH00065'),
  ('3KK00124'),
  ('3KK05584'),
  ('3KL00152'),
  ('3KL00430'),
  ('3LA00326'),
  ('3LB00292'),
  ('3LC12899'),
  ('3LC19147'),
  ('3LF00157'),
  ('3LF00279'),
  ('3LF00299'),
  ('3LH00252'),
  ('3LH00459'),
  ('3LJ01926'),
  ('3LK00432'),
  ('3LL00156'),
  ('3LL00278'),
  ('3LM00319'),
  ('3LM00435'),
  ('3LN00043'),
  ('3LN08954'),
  ('3LR00160'),
  ('3LW00187'),
  ('3LW00464'),
  ('3MA00273'),
  ('3MC00233'),
  ('3MC11054'),
  ('3MG00134'),
  ('3MG00282'),
  ('3MG11691'),
  ('3ML00192'),
  ('3MN13569'),
  ('3MR02826'),
  ('3MW11714'),
  ('3MX07491'),
  ('3NC00155'),
  ('3NF03984'),
  ('3NJ01315'),
  ('3NL00044'),
  ('3NP02253'),
  ('3NV00040'),
  ('3OG00230'),
  ('3OH00037'),
  ('3OH00073'),
  ('3ON00060'),
  ('3OP00306'),
  ('3OP01253'),
  ('3PF02759'),
  ('3QC00330'),
  ('3RB00369'),
  ('3RB00375'),
  ('3RB07724'),
  ('3RB12753'),
  ('3RF05061'),
  ('3RL00118'),
  ('3RL00204'),
  ('3RL00206'),
  ('3RL03873'),
  ('3RM00116'),
  ('3RM00358'),
  ('3RP00371'),
  ('3RP00377'),
  ('3RP04262'),
  ('3RW04286'),
  ('3SP00184'),
  ('3SP00250'),
  ('3SQ00109'),
  ('3UP14351'),
  ('3UU07513'),
  ('3WB13402'),
  ('3WI00098'),
  ('3WI00384'),
  ('3WI03465'),
  ('3WM16912'),
  ('3WQ11673'),
  ('3WS00089'),
  ('3WW00097'),
  ('3WW07134'),
  ('3WX00347'),
  ('3WX00407'),
  ('3WX07631'),
  ('3WX10767'),
  ('3WX13005'),
  ('3WY00244'),
  ('3WY00465'),
  ('3WY00468'),
  ('3WY14446'),
  ('3XA00199'),
  ('3XA09821'),
  ('3XA10721'),
  ('3XD17215'),
  ('3XU00180'),
  ('3XU22379'),
  ('3XU22434'),
  ('4AA00021'),
  ('4AC00018'),
  ('4AC00026'),
  ('4AC00027'),
  ('4AG00022'),
  ('4AG00025'),
  ('4AR00020'),
  ('4AR01236'),
  ('4BB00088'),
  ('4BB00291'),
  ('4BC11314'),
  ('4CA03618'),
  ('4CC00111'),
  ('4CC00113'),
  ('4CF19148'),
  ('4CK00275'),
  ('4CR00115'),
  ('4CR06787'),
  ('4DD00324'),
  ('4DD00331'),
  ('4DD00454'),
  ('4DD01639'),
  ('4DD03683'),
  ('4DF00164'),
  ('4DF13384'),
  ('4DH02050'),
  ('4DV02664'),
  ('4ED00423'),
  ('4ES00402'),
  ('4ES06848'),
  ('4ES11805'),
  ('4ES11978'),
  ('4EW07503'),
  ('4EW14326'),
  ('4FC00030'),
  ('4FC00176'),
  ('4FC02995'),
  ('4FC07622'),
  ('4FC11677'),
  ('4FD00001'),
  ('4FD02026'),
  ('4FD04118'),
  ('4FD05871'),
  ('4FD06346'),
  ('4FG00029'),
  ('4FG00289'),
  ('4FG01284'),
  ('4FG02943'),
  ('4FG04398'),
  ('4FG07161'),
  ('4FG13385'),
  ('4FG15438'),
  ('4FN00049'),
  ('4FY00173'),
  ('4FY02024'),
  ('4GA00012'),
  ('4GD00228'),
  ('4GF00226'),
  ('4GF14127'),
  ('4GG01946'),
  ('4GH00450'),
  ('4GI00305'),
  ('4GI02379'),
  ('4GI15439'),
  ('4GL00225'),
  ('4GL00415'),
  ('4GM00232'),
  ('4GN00231'),
  ('4GN00382'),
  ('4GN00417'),
  ('4GN00418'),
  ('4GN00419'),
  ('4HF00147'),
  ('4IG05175'),
  ('4IG07330'),
  ('4IN10857'),
  ('4JD00055'),
  ('4JJ10013'),
  ('4JN00149'),
  ('4JN00257'),
  ('4JW00057'),
  ('4LD02865'),
  ('4LF00294'),
  ('4LL00277'),
  ('4LL11499'),
  ('4LY00304'),
  ('4MA00067'),
  ('4MA00167'),
  ('4MA00312'),
  ('4NC00295'),
  ('4NJ00296'),
  ('4NM04579'),
  ('4NU04558'),
  ('4PP00350'),
  ('4PQ00352'),
  ('4PS02272'),
  ('4RA00394'),
  ('4RC03548'),
  ('4RD00207'),
  ('4RF06840'),
  ('4RL00374'),
  ('4RL00399'),
  ('4RW00208'),
  ('4RW00373'),
  ('4SB00038'),
  ('4SP12754'),
  ('4SP16859'),
  ('4SV00106'),
  ('4UW09665'),
  ('4UY07514'),
  ('4VV16856'),
  ('4WB16858'),
  ('4WI10591'),
  ('4WL15944'),
  ('4WR00045'),
  ('4WU16857'),
  ('4WU22432'),
  ('4WW17035'),
  ('4WX00405'),
  ('4WX07563'),
  ('4WX10027'),
  ('4WY07089'),
  ('4XA13770'),
  ('4XB00090'),
  ('4XU00034'),
  ('4XU05022'),
  ('4XU10872'),
  ('4XU11429'),
  ('4YE09171'),
  ('4YM00191'),
  ('4YM22431'),
  ('5ES18560'),
  ('5FC19406'),
  ('6AC09112'),
  ('6AC18110'),
  ('6AG09015'),
  ('6AG18116'),
  ('6AJ12410'),
  ('6AJ18111'),
  ('6AN07832'),
  ('6AN18003'),
  ('6AR09113'),
  ('6AR18117'),
  ('6BB07833'),
  ('6BB08505'),
  ('6BB09016'),
  ('6BB18004'),
  ('6BB18120'),
  ('6BG18119'),
  ('6BH09017'),
  ('6BH18118'),
  ('6CA07765'),
  ('6CA09018'),
  ('6CA09060'),
  ('6CA18123'),
  ('6CA18124'),
  ('6CA18126'),
  ('6CC09059'),
  ('6CC18122'),
  ('6CG13368'),
  ('6CK12391'),
  ('6CK18135'),
  ('6CL07830'),
  ('6CL09058'),
  ('6CL10386'),
  ('6CL10405'),
  ('6CL11946'),
  ('6CL18060'),
  ('6CL18121'),
  ('6CL18125'),
  ('6CL18897'),
  ('6CL18898'),
  ('6CN09093'),
  ('6CN12394'),
  ('6CN18131'),
  ('6DD08390'),
  ('6DD08537'),
  ('6DD09086'),
  ('6DD18140'),
  ('6DD18141'),
  ('6DF18006'),
  ('6DU12415'),
  ('6DU18084'),
  ('6DV09055'),
  ('6DV12422'),
  ('6DV18143'),
  ('6DV18549'),
  ('6EG08432'),
  ('6EG12402'),
  ('6EG18010'),
  ('6EG18166'),
  ('6EJ18929'),
  ('6EJ20524'),
  ('6ET18954'),
  ('6ET20539'),
  ('6EV10628'),
  ('6EV12393'),
  ('6EV18158'),
  ('6EV18167'),
  ('6EW09105'),
  ('6EW18930'),
  ('6EY09115'),
  ('6FB07709'),
  ('6FB09427'),
  ('6FB18179'),
  ('6FC08433'),
  ('6FC18181'),
  ('6FD07547'),
  ('6FD08610'),
  ('6FD09062'),
  ('6FD10042'),
  ('6FD18011'),
  ('6FD18170'),
  ('6FD18188'),
  ('6FD18956'),
  ('6FG07793'),
  ('6FG08026'),
  ('6FG08058'),
  ('6FG08392'),
  ('6FG11947'),
  ('6FG18210'),
  ('6FG18856'),
  ('6FL09127'),
  ('6FL18169'),
  ('6FN09071'),
  ('6FN09097'),
  ('6FN18183'),
  ('6FN18883'),
  ('6FQ21068'),
  ('6FV08343'),
  ('6FV09104'),
  ('6FV10907'),
  ('6FV18190'),
  ('6FV18841'),
  ('6FV18953'),
  ('6FY08507'),
  ('6FY18955'),
  ('6GB18224'),
  ('6GF07657'),
  ('6GF18175'),
  ('6GG07716'),
  ('6GG10387'),
  ('6GG18012'),
  ('6GK09255'),
  ('6GK18228'),
  ('6GL10383'),
  ('6GL18214'),
  ('6GM12399'),
  ('6GM18236'),
  ('6GN09131'),
  ('6GN18227'),
  ('6GQ09095'),
  ('6GQ18226'),
  ('6GW18223'),
  ('6HB09063'),
  ('6HB18237'),
  ('6HE09224'),
  ('6HH09096'),
  ('6HH18090'),
  ('6HL09061'),
  ('6HL11969'),
  ('6HL18013'),
  ('6HL18238'),
  ('6IA09073'),
  ('6IA09182'),
  ('6IA18014'),
  ('6IA18245'),
  ('6IF08388'),
  ('6IF18246'),
  ('6IG08436'),
  ('6IG18244'),
  ('6II13551'),
  ('6JF09428'),
  ('6JJ09085'),
  ('6JJ18250'),
  ('6JL18251'),
  ('6JN07707'),
  ('6JN07720'),
  ('6JN08956'),
  ('6JN18016'),
  ('6JN19189'),
  ('6JV10408'),
  ('6JV18248'),
  ('6KG08506'),
  ('6KG18320'),
  ('6KH08503'),
  ('6KH18319'),
  ('6KL09075'),
  ('6KL11970'),
  ('6KL18017'),
  ('6KL18318'),
  ('6LC07501'),
  ('6LF09041'),
  ('6LF09429'),
  ('6LF18321'),
  ('6LF18323'),
  ('6LJ09076'),
  ('6LJ18322'),
  ('6LL00278'),
  ('6LL00487'),
  ('6LL18018'),
  ('6LW12346'),
  ('6LW18324'),
  ('6MA20144'),
  ('6MG08411'),
  ('6MG09430'),
  ('6MG18355'),
  ('6MG18474'),
  ('6ML12398'),
  ('6ML18412'),
  ('6ML18413'),
  ('6MM08681'),
  ('6MM18498'),
  ('6NC11558'),
  ('6NC18793'),
  ('6ND09094'),
  ('6ND09418'),
  ('6ND09663'),
  ('6ND18755'),
  ('6ND18759'),
  ('6NI09419'),
  ('6NI18791'),
  ('6NJ07696'),
  ('6NJ09072'),
  ('6NJ09074'),
  ('6NJ18033'),
  ('6NJ18527'),
  ('6NJ18626'),
  ('6NL08389'),
  ('6NL08427'),
  ('6NL18079'),
  ('6NL18792'),
  ('6NM19144'),
  ('6NN09110'),
  ('6NN09420'),
  ('6NN18625'),
  ('6NN18760'),
  ('6NP08694'),
  ('6NP18957'),
  ('6ON09090'),
  ('6ON18794'),
  ('6OQ12406'),
  ('6OQ18798'),
  ('6OV09421'),
  ('6OV18034'),
  ('6PF08147'),
  ('6PF18597'),
  ('6PP09422'),
  ('6PP12412'),
  ('6PP18044'),
  ('6PP18420'),
  ('6PS12413'),
  ('6PS18638'),
  ('6QC09083'),
  ('6QC18484'),
  ('6QS09084'),
  ('6QS18438'),
  ('6QV09111'),
  ('6QV09582'),
  ('6QV10404'),
  ('6QV18045'),
  ('6QV18435'),
  ('6QV18436'),
  ('6QZ21000'),
  ('6RB00398'),
  ('6RB07924'),
  ('6RB18440'),
  ('6RB18944'),
  ('6RG12419'),
  ('6RG18421'),
  ('6RM07757'),
  ('6RM09423'),
  ('6RM18941'),
  ('6RM18942'),
  ('6RM21857'),
  ('6RR07636'),
  ('6RR07706'),
  ('6RR18074'),
  ('6SC09679'),
  ('6SC12411'),
  ('6SC12414'),
  ('6SC18557'),
  ('6SC18558'),
  ('6SC18559'),
  ('6SH09677'),
  ('6SH18444'),
  ('6SL09678'),
  ('6SL18489'),
  ('6SP09088'),
  ('6SP09163'),
  ('6SP12451'),
  ('6SP18049'),
  ('6SP18441'),
  ('6SP18442'),
  ('6SV08501'),
  ('6SV18443'),
  ('6TW08328'),
  ('6TW09087'),
  ('6TW11971'),
  ('6TW18050'),
  ('6TW18445'),
  ('6TW18844'),
  ('6UH09680'),
  ('6UH18500'),
  ('6UP07515'),
  ('6UP11559'),
  ('6UP18499'),
  ('6UQ09624'),
  ('6UQ20857'),
  ('6UQ20900'),
  ('6UT12424'),
  ('6UT18496'),
  ('6UU09106'),
  ('6UU12452'),
  ('6UU18051'),
  ('6UU18497'),
  ('6UV16208'),
  ('6UX10406'),
  ('6UX18493'),
  ('6UY09424'),
  ('6UY18081'),
  ('6VC09625'),
  ('6VD09091'),
  ('6VD18542'),
  ('6VE12421'),
  ('6VE18548'),
  ('6VF12416'),
  ('6VF18896'),
  ('6VN09081'),
  ('6VN18501'),
  ('6VN21924'),
  ('6VU09627'),
  ('6VV09134'),
  ('6VV18540'),
  ('6VW10849'),
  ('6VW18054'),
  ('6WB09123'),
  ('6WB18685'),
  ('6WC12407'),
  ('6WC18598'),
  ('6WQ08484'),
  ('6WQ18085'),
  ('6WU07495'),
  ('6WU07708'),
  ('6WU08483'),
  ('6WU18875'),
  ('6WV12277'),
  ('6WV18080'),
  ('6WW09124'),
  ('6WW18687'),
  ('6WX07911'),
  ('6WX09344'),
  ('6WX12457'),
  ('6WX18686'),
  ('6WY09425'),
  ('6WY10132'),
  ('6WY11945'),
  ('6WY18078'),
  ('6WY18600'),
  ('6WY18702'),
  ('6XB09681'),
  ('6XB18881'),
  ('6XD09426'),
  ('6XD18354'),
  ('6XU09117'),
  ('6XU09440'),
  ('6XU18055'),
  ('6XU18880'),
  ('6XU18931'),
  ('6XV09757'),
  ('6XV18882'),
  ('6XZ10738'),
  ('6XZ12347'),
  ('6YE09107'),
  ('6YE18885'),
  ('6YG07910'),
  ('6YG09070'),
  ('6YG10384'),
  ('6YG18317'),
  ('6YG18599'),
  ('6YG18895'),
  ('6YH09092'),
  ('6YH12453'),
  ('6YH18062'),
  ('6YH18894'),
  ('6ZZ00449'),
  ('6ZZ00501'),
  ('7BB00360'),
  ('7BB00414'),
  ('7BB00832'),
  ('7BH00079'),
  ('7BH00182'),
  ('7BH07692'),
  ('7CA00285'),
  ('7CA00339'),
  ('7CA00849'),
  ('7CA00857'),
  ('7CA00868'),
  ('7CC00271'),
  ('7CC00272'),
  ('7CC00280'),
  ('7CC00914'),
  ('7CH17055'),
  ('7CK00274'),
  ('7CK01077'),
  ('7CK01152'),
  ('7CL00061'),
  ('7CN00210'),
  ('7CN00318'),
  ('7CN00364'),
  ('7CR00114'),
  ('7ES01835'),
  ('7ET08078'),
  ('7GQ00200'),
  ('7HB00265'),
  ('7HB00269'),
  ('7HB00400'),
  ('7HB00404'),
  ('7HB07675'),
  ('7HB08129'),
  ('7HF00102'),
  ('7HH00104'),
  ('7HH00121'),
  ('7HH00895'),
  ('7HH00896'),
  ('7HH07671'),
  ('7HK00427'),
  ('7HL00267'),
  ('7HL10443'),
  ('7HP00403'),
  ('7HP07679'),
  ('7HS00288'),
  ('7HS00870'),
  ('7HS07556'),
  ('7HS08359'),
  ('7IS00086'),
  ('7KB00833'),
  ('7KG07758'),
  ('7KH00262'),
  ('7KH00888'),
  ('7KH08741'),
  ('7KQ00453'),
  ('7KQ07511'),
  ('7LB07762'),
  ('7LN08199'),
  ('7LW00401'),
  ('7LW00863'),
  ('7NH00426'),
  ('7NJ00081'),
  ('7NJ00472'),
  ('7NJ07496'),
  ('7NJ07740'),
  ('7OP00947'),
  ('7PH00170'),
  ('7PS00047'),
  ('7PS00342'),
  ('7PS00441'),
  ('7QC00314'),
  ('7QC00336'),
  ('7QC00561'),
  ('7QC00902'),
  ('7QK00333'),
  ('7RB00205'),
  ('7RB00900'),
  ('7RB00930'),
  ('7RL00353'),
  ('7RW00214'),
  ('7SB00041'),
  ('7SB00189'),
  ('7SC00084'),
  ('7SC00209'),
  ('7SC00327'),
  ('7SC00941'),
  ('7SE00083'),
  ('7SH00100'),
  ('7SH00198'),
  ('7SL00125'),
  ('7SP00048'),
  ('7SP00122'),
  ('7SP00123'),
  ('7SQ00359'),
  ('7SU00130'),
  ('7SV00091'),
  ('7SV00107'),
  ('7SV00108'),
  ('7SW00970'),
  ('7SW08751'),
  ('7SY07764'),
  ('7TP00822'),
  ('7TW00076'),
  ('7UQ08239'),
  ('7WB00357'),
  ('7WB13670'),
  ('7WP00844'),
  ('7WS13096'),
  ('7WU09815'),
  ('7WU09890'),
  ('7WU13382'),
  ('7WW00095'),
  ('7WW00915'),
  ('7WX00406'),
  ('7WX00917'),
  ('7WX21054'),
  ('7WX21055'),
  ('7WY00466'),
  ('7WY10413'),
  ('8FB00063'),
  ('8GE14861'),
  ('8HE00557'),
  ('8HY00554'),
  ('8HY09000'),
  ('8IG00469'),
  ('8II00243'),
  ('8JN00254'),
  ('8JN00256'),
  ('8KB00542'),
  ('8NC00338'),
  ('8ND00346'),
  ('8ND00451'),
  ('8NG00307'),
  ('8NN07699'),
  ('8NY00523'),
  ('8ON00534'),
  ('8QV18357'),
  ('8RM00395'),
  ('8RR00397'),
  ('8SW08238'),
  ('8TH08212'),
  ('8UQ08219'),
  ('8VQ00445'),
  ('8VT00635'),
  ('8VW08619'),
  ('8XU00529'),
  ('8YH00328'),
  ('8YT00576'),
  ('9DV00144'),
  ('9FC01313'),
  ('9FD00245'),
  ('9IF02656'),
  ('9IF07120'),
  ('9IR00141'),
  ('9PP00348'),
  ('9PP01951'),
  ('9PT00213'),
  ('9SP02300'),
  ('9SW00298'),
  ('9UN00235'),
  ('9UP00247'),
  ('9UU00413'),
  ('9UY19188'),
  ('9ZA17944'),
  ('ALP06024'),
  ('ALP06025'),
  ('BON06020'),
  ('BON06021'),
  ('FEM06032'),
  ('FEM06033'),
  ('MAL06022'),
  ('MAL06023'),
  ('SHAMPDRY'),
  ('TRU06028'),
  ('TRU06029'),
  ('ULT06030'),
  ('ULT06031'),
  ('UNI06026'),
  ('UNI06027')
;

WITH
profiles_to_seed AS (
  SELECT
    profile.id AS reference_profile_id,
    profile.reference_code,
    profile.name,
    profile.supplier,
    profile.abc_primary_letter,
    profile.abc_primary_family,
    profile.brief_description,
    profile.odour_description,
    profile.cas_no,
    profile.ifra_limit_percent,
    profile.life_hours
  FROM public.material_reference_profiles AS profile
  JOIN desired_reference_codes AS desired
    ON desired.reference_code = profile.reference_code
),
seeded_material_targets AS (
  SELECT
    users.id AS user_id,
    profiles.reference_profile_id,
    profiles.reference_code AS workbook_code,
    profiles.name,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'A' THEN 'A - ALI-FAT-IC'
      WHEN 'B' THEN 'B - Berg-ICEBERG'
      WHEN 'C' THEN 'C - CITRUS'
      WHEN 'D' THEN 'D - DAIRY'
      WHEN 'E' THEN 'E - EDIBLE'
      WHEN 'F' THEN 'F - FRUIT'
      WHEN 'G' THEN 'G - GREEN'
      WHEN 'H' THEN 'H - HERB (Cool)'
      WHEN 'I' THEN 'I - IRIS'
      WHEN 'J' THEN 'J - JASMIN'
      WHEN 'K' THEN 'K - KONIFER'
      WHEN 'L' THEN 'L - LIGHT Chemical Floral'
      WHEN 'M' THEN 'M - MUGUET'
      WHEN 'N' THEN 'N - NARCOTIC'
      WHEN 'O' THEN 'O - ORCHID'
      WHEN 'P' THEN 'P - PHENOL'
      WHEN 'Q' THEN 'Q - Queen of the ORIENT'
      WHEN 'R' THEN 'R - ROSE'
      WHEN 'S' THEN 'S - SPICE (Hot)'
      WHEN 'T' THEN 'T - TAR SMOKE'
      WHEN 'U' THEN 'U - Urine Faecal ANIMAL'
      WHEN 'V' THEN 'V - VANILLA'
      WHEN 'W' THEN 'W - WOOD'
      WHEN 'X' THEN 'X - X-rated MUSK'
      WHEN 'Y' THEN 'Y - EARTHY MOSSY'
      WHEN 'Z' THEN 'Z - ZOLVENTS'
      ELSE 'L - LIGHT Chemical Floral'
    END AS category,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'Z' THEN 'solvent'
      ELSE 'material'
    END AS type,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'A' THEN 'Fatty'
      WHEN 'B' THEN 'Fresh'
      WHEN 'C' THEN 'Citrus'
      WHEN 'D' THEN 'Dairy'
      WHEN 'E' THEN 'Edible'
      WHEN 'F' THEN 'Fruity'
      WHEN 'G' THEN 'Green'
      WHEN 'H' THEN 'Herbal'
      WHEN 'I' THEN 'Powdery'
      WHEN 'J' THEN 'Floral'
      WHEN 'K' THEN 'Coniferous'
      WHEN 'L' THEN 'Floral'
      WHEN 'M' THEN 'Floral'
      WHEN 'N' THEN 'Floral'
      WHEN 'O' THEN 'Floral'
      WHEN 'P' THEN 'Phenolic'
      WHEN 'Q' THEN 'Resinous'
      WHEN 'R' THEN 'Rose'
      WHEN 'S' THEN 'Spicy'
      WHEN 'T' THEN 'Smoky'
      WHEN 'U' THEN 'Animalic'
      WHEN 'V' THEN 'Gourmand'
      WHEN 'W' THEN 'Woody'
      WHEN 'X' THEN 'Musky'
      WHEN 'Y' THEN 'Earthy'
      WHEN 'Z' THEN 'Solvent'
      ELSE 'Floral'
    END AS scent_family,
    1000::numeric(12, 2) AS stock_quantity,
    'ml'::text AS unit,
    0::numeric(12, 2) AS cost_per_unit,
    1::numeric(12, 2) AS minimum_stock,
    1::numeric(12, 2) AS low_stock_threshold,
    profiles.supplier AS supplier_name,
    profiles.supplier AS vendor,
    profiles.cas_no AS cas_number,
    CASE
      WHEN profiles.ifra_limit_percent IS NULL THEN NULL
      WHEN profiles.ifra_limit_percent < 0 THEN NULL
      WHEN profiles.ifra_limit_percent > 100 THEN NULL
      ELSE profiles.ifra_limit_percent
    END AS ifra_limit,
    CASE
      WHEN profiles.life_hours IS NULL THEN NULL
      WHEN profiles.life_hours < 12 THEN 'top'
      WHEN profiles.life_hours < 120 THEN 'middle'
      ELSE 'base'
    END AS pyramid_placement,
    coalesce(nullif(trim(profiles.brief_description), ''), nullif(trim(profiles.odour_description), '')) AS description,
    concat_ws(
      ' ',
      'Seeded from Perfumer''s Workbook reference library.',
      concat('Reference code: ', profiles.reference_code),
      CASE WHEN profiles.supplier IS NOT NULL THEN concat('Workbook supplier: ', profiles.supplier) END
    ) AS notes
  FROM auth.users AS users
  CROSS JOIN profiles_to_seed AS profiles
),
legacy_seeded_rows AS (
  SELECT raw_material.id
  FROM public.raw_materials AS raw_material
  WHERE raw_material.workbook_code IS NOT NULL
    AND raw_material.notes LIKE 'Seeded from Perfumer''s Workbook reference library.%'
    AND NOT EXISTS (
      SELECT 1
      FROM desired_reference_codes AS desired
      WHERE desired.reference_code = raw_material.workbook_code
    )
)
DELETE FROM public.raw_material_reference_links AS link
WHERE EXISTS (
  SELECT 1
  FROM legacy_seeded_rows AS legacy
  WHERE legacy.id = link.raw_material_id
);

WITH
legacy_seeded_rows AS (
  SELECT raw_material.id
  FROM public.raw_materials AS raw_material
  WHERE raw_material.workbook_code IS NOT NULL
    AND raw_material.notes LIKE 'Seeded from Perfumer''s Workbook reference library.%'
    AND NOT EXISTS (
      SELECT 1
      FROM desired_reference_codes AS desired
      WHERE desired.reference_code = raw_material.workbook_code
    )
)
DELETE FROM public.raw_materials AS raw_material
WHERE EXISTS (
  SELECT 1
  FROM legacy_seeded_rows AS legacy
  WHERE legacy.id = raw_material.id
);

WITH
profiles_to_seed AS (
  SELECT
    profile.id AS reference_profile_id,
    profile.reference_code,
    profile.name,
    profile.supplier,
    profile.abc_primary_letter,
    profile.abc_primary_family,
    profile.brief_description,
    profile.odour_description,
    profile.cas_no,
    profile.ifra_limit_percent,
    profile.life_hours
  FROM public.material_reference_profiles AS profile
  JOIN desired_reference_codes AS desired
    ON desired.reference_code = profile.reference_code
),
seeded_material_targets AS (
  SELECT
    users.id AS user_id,
    profiles.reference_profile_id,
    profiles.reference_code AS workbook_code,
    profiles.name,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'A' THEN 'A - ALI-FAT-IC'
      WHEN 'B' THEN 'B - Berg-ICEBERG'
      WHEN 'C' THEN 'C - CITRUS'
      WHEN 'D' THEN 'D - DAIRY'
      WHEN 'E' THEN 'E - EDIBLE'
      WHEN 'F' THEN 'F - FRUIT'
      WHEN 'G' THEN 'G - GREEN'
      WHEN 'H' THEN 'H - HERB (Cool)'
      WHEN 'I' THEN 'I - IRIS'
      WHEN 'J' THEN 'J - JASMIN'
      WHEN 'K' THEN 'K - KONIFER'
      WHEN 'L' THEN 'L - LIGHT Chemical Floral'
      WHEN 'M' THEN 'M - MUGUET'
      WHEN 'N' THEN 'N - NARCOTIC'
      WHEN 'O' THEN 'O - ORCHID'
      WHEN 'P' THEN 'P - PHENOL'
      WHEN 'Q' THEN 'Q - Queen of the ORIENT'
      WHEN 'R' THEN 'R - ROSE'
      WHEN 'S' THEN 'S - SPICE (Hot)'
      WHEN 'T' THEN 'T - TAR SMOKE'
      WHEN 'U' THEN 'U - Urine Faecal ANIMAL'
      WHEN 'V' THEN 'V - VANILLA'
      WHEN 'W' THEN 'W - WOOD'
      WHEN 'X' THEN 'X - X-rated MUSK'
      WHEN 'Y' THEN 'Y - EARTHY MOSSY'
      WHEN 'Z' THEN 'Z - ZOLVENTS'
      ELSE 'L - LIGHT Chemical Floral'
    END AS category,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'Z' THEN 'solvent'
      ELSE 'material'
    END AS type,
    CASE upper(coalesce(profiles.abc_primary_letter, ''))
      WHEN 'A' THEN 'Fatty'
      WHEN 'B' THEN 'Fresh'
      WHEN 'C' THEN 'Citrus'
      WHEN 'D' THEN 'Dairy'
      WHEN 'E' THEN 'Edible'
      WHEN 'F' THEN 'Fruity'
      WHEN 'G' THEN 'Green'
      WHEN 'H' THEN 'Herbal'
      WHEN 'I' THEN 'Powdery'
      WHEN 'J' THEN 'Floral'
      WHEN 'K' THEN 'Coniferous'
      WHEN 'L' THEN 'Floral'
      WHEN 'M' THEN 'Floral'
      WHEN 'N' THEN 'Floral'
      WHEN 'O' THEN 'Floral'
      WHEN 'P' THEN 'Phenolic'
      WHEN 'Q' THEN 'Resinous'
      WHEN 'R' THEN 'Rose'
      WHEN 'S' THEN 'Spicy'
      WHEN 'T' THEN 'Smoky'
      WHEN 'U' THEN 'Animalic'
      WHEN 'V' THEN 'Gourmand'
      WHEN 'W' THEN 'Woody'
      WHEN 'X' THEN 'Musky'
      WHEN 'Y' THEN 'Earthy'
      WHEN 'Z' THEN 'Solvent'
      ELSE 'Floral'
    END AS scent_family,
    1000::numeric(12, 2) AS stock_quantity,
    'ml'::text AS unit,
    0::numeric(12, 2) AS cost_per_unit,
    1::numeric(12, 2) AS minimum_stock,
    1::numeric(12, 2) AS low_stock_threshold,
    profiles.supplier AS supplier_name,
    profiles.supplier AS vendor,
    profiles.cas_no AS cas_number,
    CASE
      WHEN profiles.ifra_limit_percent IS NULL THEN NULL
      WHEN profiles.ifra_limit_percent < 0 THEN NULL
      WHEN profiles.ifra_limit_percent > 100 THEN NULL
      ELSE profiles.ifra_limit_percent
    END AS ifra_limit,
    CASE
      WHEN profiles.life_hours IS NULL THEN NULL
      WHEN profiles.life_hours < 12 THEN 'top'
      WHEN profiles.life_hours < 120 THEN 'middle'
      ELSE 'base'
    END AS pyramid_placement,
    coalesce(nullif(trim(profiles.brief_description), ''), nullif(trim(profiles.odour_description), '')) AS description,
    concat_ws(
      ' ',
      'Seeded from Perfumer''s Workbook reference library.',
      concat('Reference code: ', profiles.reference_code),
      CASE WHEN profiles.supplier IS NOT NULL THEN concat('Workbook supplier: ', profiles.supplier) END
    ) AS notes
  FROM auth.users AS users
  CROSS JOIN profiles_to_seed AS profiles
)
INSERT INTO public.raw_materials (
  user_id, name, category, type, scent_family, stock_quantity, unit, cost_per_unit,
  minimum_stock, low_stock_threshold, supplier_name, vendor, cas_number, ifra_limit,
  pyramid_placement, description, notes, workbook_code
)
SELECT
  seed.user_id, seed.name, seed.category, seed.type, seed.scent_family, seed.stock_quantity,
  seed.unit, seed.cost_per_unit, seed.minimum_stock, seed.low_stock_threshold, seed.supplier_name,
  seed.vendor, seed.cas_number, seed.ifra_limit, seed.pyramid_placement, seed.description, seed.notes,
  seed.workbook_code
FROM seeded_material_targets AS seed
WHERE NOT EXISTS (
  SELECT 1
  FROM public.raw_materials AS existing_raw_material
  WHERE existing_raw_material.user_id = seed.user_id
    AND (
      existing_raw_material.workbook_code = seed.workbook_code
      OR lower(trim(existing_raw_material.name)) = lower(trim(seed.name))
    )
);

WITH
profiles_to_seed AS (
  SELECT
    profile.id AS reference_profile_id,
    profile.reference_code,
    profile.name,
    profile.supplier,
    profile.abc_primary_letter,
    profile.abc_primary_family,
    profile.brief_description,
    profile.odour_description,
    profile.cas_no,
    profile.ifra_limit_percent,
    profile.life_hours
  FROM public.material_reference_profiles AS profile
  JOIN desired_reference_codes AS desired
    ON desired.reference_code = profile.reference_code
)
INSERT INTO public.raw_material_reference_links (
  raw_material_id, reference_profile_id, match_method, match_confidence, is_primary, notes
)
SELECT
  raw_material.id,
  profile.reference_profile_id,
  'seeded_workbook_library',
  1,
  true,
  'Linked while seeding workbook inventory library.'
FROM public.raw_materials AS raw_material
JOIN profiles_to_seed AS profile
  ON profile.reference_code = raw_material.workbook_code
WHERE NOT EXISTS (
  SELECT 1
  FROM public.raw_material_reference_links AS existing_link
  WHERE existing_link.raw_material_id = raw_material.id
    AND existing_link.is_primary = true
);

COMMIT;
