export const PERFUMERS_WORLD_CATEGORIES = [
  {
    code: 'A',
    name: 'ALI-FAT-IC',
    label: 'A - ALI-FAT-IC',
    description: 'Fatty, waxy, soapy, clean',
    reference: 'Aliphatic aldehydes, alcohols',
    color: '#D9E2EC',
  },
  {
    code: 'B',
    name: 'Berg-ICEBERG',
    label: 'B - Berg-ICEBERG',
    description: 'Cooling, borneol, mint, camphor',
    reference: 'Menthol, camphor, eucalyptol',
    color: '#D6F5FF',
  },
  {
    code: 'C',
    name: 'CITRUS',
    label: 'C - CITRUS',
    description: 'Sour, sharp, citrus peel',
    reference: 'Citral, orange, lemon, lime',
    color: '#FFD166',
  },
  {
    code: 'D',
    name: 'DAIRY',
    label: 'D - DAIRY',
    description: 'Milky, cream, butter, cheese',
    reference: 'Diacetyl, butyrate, lactone, valerate',
    color: '#FFF1CC',
  },
  {
    code: 'E',
    name: 'EDIBLE',
    label: 'E - EDIBLE',
    description: 'Vegetable, nut, fish, meat',
    reference: 'Thiazoles, pyrazines, sulphides',
    color: '#DDB892',
  },
  {
    code: 'F',
    name: 'FRUIT',
    label: 'F - FRUIT',
    description: 'Sour, sweet fruits, strawberry',
    reference: 'Allyl caproate, Verdox',
    color: '#FF8FA3',
  },
  {
    code: 'G',
    name: 'GREEN',
    label: 'G - GREEN',
    description: 'Cut-grass, leaves',
    reference: 'cis-3-Hexenol, Triplal',
    color: '#7BC47F',
  },
  {
    code: 'H',
    name: 'HERB (Cool)',
    label: 'H - HERB (Cool)',
    description: 'Cool herbaceous notes',
    reference: 'Lavender, sage',
    color: '#8FBF8F',
  },
  {
    code: 'I',
    name: 'IRIS',
    label: 'I - IRIS',
    description: 'Orris, violet',
    reference: 'Ionones, methyl ionone',
    color: '#B8A1E3',
  },
  {
    code: 'J',
    name: 'JASMIN',
    label: 'J - JASMIN',
    description: 'Fruity, oily, narcotic, jasmin',
    reference: 'HCA, benzyl acetate',
    color: '#FFF4D6',
  },
  {
    code: 'K',
    name: 'KONIFER',
    label: 'K - KONIFER',
    description: 'Pine, pine needle',
    reference: 'Terpineol, bornyl acetate',
    color: '#6B8E23',
  },
  {
    code: 'L',
    name: 'LIGHT Chemical Floral',
    label: 'L - LIGHT Chemical Floral',
    description: 'Fresh light floral chemical',
    reference: 'Linalool, Vertenex, DMBC',
    color: '#FDE68A',
  },
  {
    code: 'M',
    name: 'MUGUET',
    label: 'M - MUGUET',
    description: 'Lily of the valley, green, fresh',
    reference: 'Hydroxy, Lilial, Lyral',
    color: '#CDECCF',
  },
  {
    code: 'N',
    name: 'NARCOTIC',
    label: 'N - NARCOTIC',
    description: 'Heavy sweet florals, absolutes',
    reference: 'Narcissus, Ylang Ylang, Tuberose',
    color: '#A16207',
  },
  {
    code: 'O',
    name: 'ORCHID',
    label: 'O - ORCHID',
    description: 'Aromatic, deep floral',
    reference: 'Salicylates, benzoates',
    color: '#A855F7',
  },
  {
    code: 'P',
    name: 'PHENOL',
    label: 'P - PHENOL',
    description: 'Phenol, medicinal, honey',
    reference: 'p-Cresol, Ethyl Phenyl Acetate',
    color: '#6B7280',
  },
  {
    code: 'Q',
    name: 'Queen of the ORIENT',
    label: 'Q - Queen of the ORIENT',
    description: 'Resin, balsam',
    reference: 'Benzoin, Tolu, Terpenes',
    color: '#F59E0B',
  },
  {
    code: 'R',
    name: 'ROSE',
    label: 'R - ROSE',
    description: 'Rose otto, absolute, geranium',
    reference: 'Citronellol, PEA, Rhodinol',
    color: '#F9A8D4',
  },
  {
    code: 'S',
    name: 'SPICE (Hot)',
    label: 'S - SPICE (Hot)',
    description: 'Hot culinary spice',
    reference: 'Clove, Cinnamon, Thyme',
    color: '#F97316',
  },
  {
    code: 'T',
    name: 'TAR SMOKE',
    label: 'T - TAR SMOKE',
    description: 'Smoke, tar, burnt',
    reference: 'Cade, Birch Tar',
    color: '#1F2937',
  },
  {
    code: 'U',
    name: 'Urine Faecal ANIMAL',
    label: 'U - Urine Faecal ANIMAL',
    description: 'Animal, faecal, leather',
    reference: 'Civet, Castoreum, Ambergris',
    color: '#8B5E3C',
  },
  {
    code: 'V',
    name: 'VANILLA',
    label: 'V - VANILLA',
    description: 'Sweet edible vanilla',
    reference: 'Vanillin, Coumarin, Heliotropin',
    color: '#C08457',
  },
  {
    code: 'W',
    name: 'WOOD',
    label: 'W - WOOD',
    description: 'Wood, oily, cedar, santal',
    reference: 'Vetivert, Patchouli',
    color: '#8B5A3C',
  },
  {
    code: 'X',
    name: 'X-rated MUSK',
    label: 'X - X-rated MUSK',
    description: 'Sexy, musk, sensual, sweet',
    reference: 'Musk Ketone, Galaxolide',
    color: '#CBD5E1',
  },
  {
    code: 'Y',
    name: 'EARTHY MOSSY',
    label: 'Y - EARTHY MOSSY',
    description: 'Yeast, fungal, moss, marine',
    reference: 'Oakmoss, Calone',
    color: '#4B5563',
  },
  {
    code: 'Z',
    name: 'ZOLVENTS',
    label: 'Z - ZOLVENTS',
    description: 'Odourless solvents, solubilisers',
    reference: 'DEP, DPG, IPP, Ethanol, PG',
    color: '#60A5FA',
  },
];

export const getPerfumersWorldCategoryOptions = () =>
  PERFUMERS_WORLD_CATEGORIES.map((category) => ({
    value: category.label.toLowerCase(),
    label: `${category.label} - ${category.description}`,
  }));

export const findPerfumersWorldCategoryByValue = (value) =>
  PERFUMERS_WORLD_CATEGORIES.find((category) => category.label.toLowerCase() === String(value || '').toLowerCase()) || null;

export const findPerfumersWorldCategoryByCode = (code) =>
  PERFUMERS_WORLD_CATEGORIES.find((category) => category.code.toLowerCase() === String(code || '').toLowerCase()) || null;

export const PERFUMERS_WORLD_CATEGORY_VALUES = new Set(
  PERFUMERS_WORLD_CATEGORIES.map((category) => category.label.toLowerCase())
);
